In [2]:
import numpy as np
A= np.array([[9, 8], [7,6]])
B= np.array([[5, 4], [3, 2]])
print(A+B)

[[14 12]
 [10  8]]


In [10]:
print (A - B)  # This will also print the result of A + B


[[4 4]
 [4 4]]


In [ ]:
mul=np.dot(A, B)
print(mul)  # This will print the result of the matrix multiplication A * B
#9*5 + 8*3, 9*4 + 8*2
#8*5 + 6*3, 8*4 + 6*2
#[a1,a2] [a3.a4], [b1,b2], [b3,b4] = # [[a1*b1 + a2*b3, a1*b2 + a2*b4], [a3*b1 + a4*b3, a3*b2 + a4*b4]]
#first row of A with first column of B, first row of A with second column of B
#second row of A with first column of B, second row of A with second column of B

[[69 52]
 [53 40]]


In [13]:
print(np.eye(2))  # This will create a 2x2 identity matrix
print(np.ones((2, 2)))  # This will create a 2x2 matrix filled with ones
print(np.zeros((2, 2)) ) # This will create a 2x2 matrix filled with zeros
print(np.full((2, 2), 7))  # This will create a 2x2 matrix filled with the value 7
print(np.random.rand(2, 2))  # This will create a 2x2 matrix with random values between 0 and 1
print(np.random.randint(1, 10, (2, 2)))  # This will create a 2x2 matrix with random integers between 1 and 10
print(np.random.randn(2, 2))  # This will create a 2x2 matrix with random values from a standard normal distribution
print(np.random.seed(0))  # Setting a seed for reproducibility


[[1. 0.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]
[[7 7]
 [7 7]]
[[0.5488135  0.71518937]
 [0.60276338 0.54488318]]
[[4 6]
 [3 5]]
[[-0.29139398 -0.13309028]
 [-0.1730696  -1.76165167]]
None


In [ ]:
print(np.diag(A))  # This will extract the diagonal elements of matrix A
# np.diag(A) returns the diagonal elements of matrix A as a 1D array.
# For A = [[9, 8], [7, 6]], the diagonal elements are 9 and 6, so it returns [9 6].

# np.diag(B) does the same for matrix B, returning [5 2].

# np.diagflat(A) takes all elements of A, flattens them into a 1D array, and creates a 2D diagonal matrix with those elements on the diagonal.
# For A = [[9, 8], [7, 6]], it flattens to [9, 8, 7, 6] and creates a 4x4 matrix with these values on the diagonal.

# np.trace(A) computes the sum of the diagonal elements of A.
# For A, the trace is 9 + 6 = 15.

# np.trace(B) computes the sum of the diagonal elements of B.
# For B, the trace is 5 + 2 = 7.
print(np.diag(B))  # This will extract the diagonal elements of matrix B

print(np.diagflat(A))  # This will create a diagonal matrix from the elements of A elements)
print(np.diagflat(B))  # This will create a diagonal matrix from the elements of B

print(np.trace(A))  # This will calculate the trace of matrix A (sum of diagonal elements)
print(np.trace(B))  # This will calculate the trace of matrix B (sum of diagonal


[9 6]
[5 2]
[[9 0 0 0]
 [0 8 0 0]
 [0 0 7 0]
 [0 0 0 6]]
[[5 0 0 0]
 [0 4 0 0]
 [0 0 3 0]
 [0 0 0 2]]
15
7


In [3]:
print("Scalar multiplication of A by 2:", A * 2)  # This will multiply each element of A by 2
print("Scalar multiplication of B by 3:", B * 3)  # This will multiply each element of B by 3
# Explanation:
# Scalar multiplication in numpy means multiplying every element of the array by the scalar value.
# Here, B * 3 multiplies each element of matrix B by 3:
# [[5, 4],      [[5*3, 4*3],      [[15, 12],
#  [3, 2]]  *    3   [3*3, 2*3]] =  [9, 6]]
# The result is a new matrix where each element is three times the corresponding element in B.



Scalar multiplication of A by 2: [[18 16]
 [14 12]]
Scalar multiplication of B by 3: [[15 12]
 [ 9  6]]


In [4]:
np.diag([1,2,3,4])  # This will create a diagonal matrix with the elements 1, 2, 3, and 4 on the diagonal
# Explanation:
# np.diag([1,2,3,4]) creates a square matrix with the input list elements on its main diagonal.
# The result will be:
# [[1 0 0 0]
#  [0 2 0 0]
#  [0 0 3 0]
#  [0 0 0 4]]
# All off-diagonal elements are zero.

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [5]:
np.linalg.det(A)  # This will calculate the determinant of matrix A
# Explanation:
# np.linalg.det(A) computes the determinant of the matrix A.
# For a 2x2 matrix [[a, b], [c, d]], the determinant is (a*d - b*c).
# For A = [[9, 8], [7, 6]], the determinant is (9*6 - 8*7) = (54 - 56) = -2.

np.float64(-1.9999999999999931)

In [6]:
print(np.linalg.inv(A))  # This will calculate the inverse of matrix A
# Explanation:
# np.linalg.inv(A) computes the inverse of the matrix A.
# For a 2x2 matrix [[a, b], [c, d]], the inverse is (1/det(A)) * [[d, -b], [-c, a]].
# For A = [[9, 8], [7, 6]], the determinant is -2.
# So, the inverse is (1/-2) * [[6, -8], [-7, 9]] = [[-3, 4], [3.5, -4.5]].

[[-3.   4. ]
 [ 3.5 -4.5]]


In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(A)  # This will calculate the eigenvalues and eigenvectors of matrix A
print("Eigenvalues of A:", eigenvalues)
print("Eigenvectors of A:\n", eigenvectors)
# Explanation:
# To find the eigenvalues of A, we solve the characteristic equation:
#   det(A - λI) = 0
# For A = [[9, 8], [7, 6]], this becomes:
#   |9-λ   8  |
#   | 7   6-λ| = (9-λ)*(6-λ) - (8*7) = 0
#   (9-λ)*(6-λ) - 56 = 0
#   (54 - 9λ - 6λ + λ^2) - 56 = 0
#   λ^2 - 15λ - 2 = 0
# Solving this quadratic equation:
#   λ = [15 ± sqrt(15^2 + 8)] / 2 = [15 ± sqrt(229)] / 2
#   sqrt(229) ≈ 15.13216876, so
#   λ1 ≈ (15 + 15.13216876)/2 ≈ 15.13216876/2 ≈ 15.13216876 (since the quadratic formula is λ = [15 ± sqrt(229)]/2)
#   λ2 ≈ (15 - 15.13216876)/2 ≈ -0.13216876
# These are the eigenvalues: [15.13216876, -0.13216876]

# To find the eigenvectors, for each eigenvalue λ, solve (A - λI)v = 0:
# For λ1 ≈ 15.13216876:
#   (A - λ1*I) = [[9-15.13216876, 8], [7, 6-15.13216876]]
#   This gives a system of equations for v = [x, y]:
#     (9-λ1)x + 8y = 0
#     7x + (6-λ1)y = 0
#   Solving for the ratio x/y gives the direction of the eigenvector.
#   The resulting eigenvector is normalized to unit length, giving [0.79366214, 0.60835878].

# For λ2 ≈ -0.13216876:
#   (A - λ2*I) = [[9+0.13216876, 8], [7, 6+0.13216876]]
#   Similarly, solve for the eigenvector direction and normalize, giving [-0.65894079, 0.75219481].

# The columns of the eigenvectors array correspond to the normalized eigenvectors for each eigenvalue.

# 1. np.linalg.eig(A) computes the eigenvalues and eigenvectors of the square matrix A.
#    - Eigenvalues are scalars λ such that there exists a non-zero vector v (the eigenvector) satisfying A*v = λ*v.
#    - The function returns two objects:
#        a) eigenvalues: a 1D array containing the eigenvalues of A.
#        b) eigenvectors: a 2D array where each column is an eigenvector corresponding to an eigenvalue.
# 2. The eigenvectors are normalized to have unit length.
# 3. The print statements display the eigenvalues and eigenvectors for inspection.

# Limitations:
# - The input matrix A must be square (same number of rows and columns).
# - For matrices with complex eigenvalues or eigenvectors, the output will contain complex numbers.
# - Numerical precision issues may arise for large or ill-conditioned matrices.
# - For defective matrices (matrices that do not have a complete set of linearly independent eigenvectors), the results may not be meaningful or may not exist in the real domain.
# np.linalg.eig(A) computes the eigenvalues and eigenvectors of the matrix A.
# The eigenvalues are returned in the array 'eigenvalues'.
# The columns of the matrix 'eigenvectors' are the normalized eigenvectors corresponding to each eigenvalue.
# For matrix A = [[9, 8], [7, 6]], this function finds λ and v such that A*v = λ*v.

Eigenvalues of A: [15.13216876 -0.13216876]
Eigenvectors of A:
 [[ 0.79366214 -0.65894079]
 [ 0.60835878  0.75219481]]


In [ ]:
U, S,Vt = np.linalg.svd(A)  # This will perform Singular Value Decomposition (SVD) on matrix A
print("U matrix:\n", U)  # This will print the U matrix from S
print("S values:", S)  # This will print the singular values from SVD
print("Vt matrix:\n", Vt)  # This will print the V transpose
# Explanation:
# 1. How it is executed with explanation in detail:
#    - np.linalg.svd(A) performs Singular Value Decomposition (SVD) on matrix A.
#    - It decomposes A into three matrices: U, S, and Vt such that A = U @ np.diag(S) @ Vt.
#      - U: Unitary matrix containing the left singular vectors.
#      - S: 1D array of singular values (sorted in descending order).
#      - Vt: Unitary matrix containing the right singular vectors (transposed).
#    - This is useful for analyzing the structure of A, solving linear systems, and more.

# 2. Is there any limitation:
#    - SVD is computationally expensive for very large matrices.
#    - For non-square matrices, U and Vt will have different shapes.
#    - Numerical precision issues may arise for ill-conditioned matrices.
#    - SVD always exists for any real or complex matrix, but the computation may be slow for large datasets.

# 3. Why we use it:
#    - SVD is used for dimensionality reduction (e.g., PCA), noise reduction, and data compression.
#    - It helps in solving linear systems, computing pseudoinverses, and matrix approximation.
#    - It reveals important properties of the matrix, such as rank and range.

# 4. When/where to use it:
#    - In machine learning for Principal Component Analysis (PCA).
#    - In signal processing for noise reduction.
#    - In recommender systems (e.g., collaborative filtering).
#    - For solving least squares problems and computing the pseudoinverse of a matrix.

# 5. Different ways or how to use it:
#    - Full SVD: U, S, Vt = np.linalg.svd(A)
#    - Reduced SVD: U, S, Vt = np.linalg.svd(A, full_matrices=False)
#    - To reconstruct the original matrix: A_reconstructed = U @ np.diag(S) @ Vt
# Step-by-step explanation of SVD on matrix A:
# 1. We call np.linalg.svd(A), where A is:
#    [[9, 8],
#     [7, 6]]
# 2. SVD decomposes A into three parts: U, S, and Vt.
#    - U: Contains the left singular vectors (columns are special directions in the input space).
#    - S: Contains the singular values (strengths of each direction).
#    - Vt: Contains the right singular vectors (rows are special directions in the output space).
# 3. The shapes:
#    - U is 2x2, S is length 2, Vt is 2x2 (since A is 2x2).
# 4. You can reconstruct A using: U @ np.diag(S) @ Vt
#    - np.diag(S) makes a diagonal matrix from S.
#    - "@" means matrix multiplication.
# 5. The printed output shows:
#    - U: the left singular vectors.
#    - S: the singular values.
#    - Vt: the right singular vectors (transposed).
#    - These values are calculated by numpy for you.
#    - The SVD always works for any matrix, and helps us understand its structure.
#    - For sparse matrices, use scipy.sparse.linalg.svds for efficiency.
# Let's break down how the SVD output values for matrix A were obtained:

# 1. SVD decomposes A into U, S, and Vt such that A = U @ np.diag(S) @ Vt.
#    For A = [[9, 8], [7, 6]], numpy computes:
#    - U: left singular vectors (orthogonal, columns are eigenvectors of AA^T)
#    - S: singular values (square roots of eigenvalues of AA^T or A^TA, sorted descending)
#    - Vt: right singular vectors (orthogonal, rows are eigenvectors of A^TA)

# 2. Compute A^T A and A A^T:
#    A^T A = [[9, 7], [8, 6]] @ [[9, 8], [7, 6]] = [[130, 110], [110, 100]]
#    A A^T = [[9, 8], [7, 6]] @ [[9, 7], [8, 6]] = [[145, 125], [125, 85]]

# 3. The eigenvalues of A^T A (or A A^T) are the squares of the singular values:
#    - Compute eigenvalues of A^T A: λ1 ≈ 229.999999, λ2 ≈ 0.017379
#    - Singular values S = sqrt([229.999999, 0.017379]) ≈ [15.16517746, 0.13188108]

# 4. The columns of U are the normalized eigenvectors of A A^T:
#    - These are computed numerically by numpy, resulting in:
#      [[-0.79401166, -0.60790253],
#       [-0.60790253,  0.79401166]]

# 5. The rows of Vt are the normalized eigenvectors of A^T A:
#    - Also computed numerically, giving:
#      [[-0.75181597, -0.65937299],
#       [ 0.65937299, -0.75181597]]

# 6. The SVD guarantees that U and Vt are orthogonal (U.T @ U = I, Vt @ Vt.T = I), and S contains the singular values in descending order.

# In summary:
# - S values are the square roots of the eigenvalues of A^T A (or A A^T).
# - U columns are eigenvectors of A A^T.
# - Vt rows are eigenvectors of A^T A.
# - Numpy's np.linalg.svd computes these numerically for you.


U matrix:
 [[-0.79401166 -0.60790253]
 [-0.60790253  0.79401166]]
S values: [15.16517746  0.13188108]
Vt matrix:
 [[-0.75181597 -0.65937299]
 [ 0.65937299 -0.75181597]]


In [ ]:
import sympy as sp
