In [2]:
import numpy as np
li= [1,2,3]
nu_li = np.array(li)
print([x*2 for x in li])
print(nu_li*2)

[2, 4, 6]
[2 4 6]


In [3]:
import numpy as np
arr=np.arange(6)
print(arr)
print(arr.reshape(2,3))
print(arr.ravel())

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


In [8]:
data = [
    [11,12,13,14],
    [21,22,23,24],
    [31,32,33,34],
    [41,42,43,44]
]

arr = np.array(data)
print(arr)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]


In [9]:
arr.mean(axis=0)  # Mean of each column
print(arr.mean(axis=0))
arr.mean(axis=1)  # Mean of each row
print(arr.mean(axis=1))
arr.sum(axis=0)  # Sum of each column
print(arr.sum(axis=0))
arr.sum(axis=1)  # Sum of each row
print(arr.sum(axis=1))

[26. 27. 28. 29.]
[12.5 22.5 32.5 42.5]
[104 108 112 116]
[ 50  90 130 170]


In [6]:
import numpy as np

arr = np.random.rand(3, 4)
print("Original Array:\n", arr)

squared_arr = arr ** 2
print("\nSquared Array:\n", squared_arr)

greater_than_0_5 = squared_arr[squared_arr > 0.5]
print("\nElements greater than 0.5:\n", greater_than_0_5)

Original Array:
 [[0.45751724 0.95889969 0.81881474 0.74109801]
 [0.72005933 0.99285143 0.91610695 0.13624112]
 [0.3069009  0.14359081 0.13313908 0.5734439 ]]

Squared Array:
 [[0.20932202 0.91948861 0.67045758 0.54922625]
 [0.51848543 0.98575395 0.83925195 0.01856164]
 [0.09418816 0.02061832 0.01772602 0.32883791]]

Elements greater than 0.5:
 [0.91948861 0.67045758 0.54922625 0.51848543 0.98575395 0.83925195]
